### ISSUE TITLE
OS X Release 12.6.1 breaks vendored libpg_query

### ISSUE THREAD

**Issue by pm-mck** [roddyyaga/pg_query-ocaml#11]
The most recent update to XCode breaks the build due to a naming conflict with a `#define`.

See 
https://github.com/pganalyze/pg_query/issues/263 
and 
https://github.com/postgres/postgres/commit/bc7a40b42eef717026d29b687157cd0af5adaadb 
for more details.

**Comment by roddyyaga** [comment]
Fixed by @JulesGuesnon's PR :)
