### ISSUE TITLE
Use stdlib instead of janestreet core?

### ISSUE THREAD

**Issue by eWert-Online** [roddyyaga/pg_query-ocaml#3]
As far as I can see, core is only used in one file. 
As it is a really big package with lots of dependencies, it really slows down build times. 
Would it be ok to remove it and use the ocaml stdlib instead or is this not possible?

If you would consider it, I could also try to submit a PR. 

Thank you! 😊

**Comment by roddyyaga** [comment]
Hey, I think it would be possible to remove it (probably cmdliner would be needed as a substitute), but I don't think I will have time any time soon. A PR to do it would definitely be welcome though! Another option for a PR would be to make the dependency on Core and the executable in dune both optional (I assume you are using the library not the executable).

**Comment by eWert-Online** [comment]
Thanks for the quick response. 
Yeah I also thought that it would be an option to split the cli and library into different packages altogether.

I will see, if I have time to submit a pr soon. Thanks!
