### ISSUE TITLE
cmdliner deprecations

### ISSUE THREAD

**Issue by phstrauss** [roddyyaga/pg_query-ocaml#9]
Hello,

I've tried to build pg_query from source using this repos and got the following errors/warings, using OCaml 4.13.1 and fresh dune install, opam is 2.0.5 from ubuntu 20.4:

`~/Sources/Workbench/pg_query-ocaml-git$ dune build
File "dune-project", line 1, characters 11-16:
1 | (lang dune 2.0.1)
               ^^^^^
Warning: The ".1" part is ignored here.
This version is parsed as just 2.0.
File "test/dune", line 2, characters 8-12:
2 |  (names test)
            ^^^^
Error: No rule found for lib/dllpg_query.so
File "bin/pg_check.ml", line 47, characters 2-11:
47 |   Term.info "pg_check" 
       ^^^^^^^^^
Error (alert deprecated): Cmdliner.Term.info
Use Cmd.info instead.
File "bin/pg_check.ml", line 51, characters 6-15:
51 |       exit_info 0 ~doc:"if all files were parsed successfully.";
           ^^^^^^^^^
Error (alert deprecated): Cmdliner.Term.exit_info
Use Cmd.Exit.info instead.
File "bin/pg_check.ml", line 52, characters 6-15:
52 |       exit_info 1 ~doc:"on parsing errors.";
           ^^^^^^^^^
Error (alert deprecated): Cmdliner.Term.exit_info
Use Cmd.Exit.info instead.
File "bin/pg_check.ml", line 53, characters 6-15:
53 |       exit_info 124 ~doc:"on command line parsing errors.";
           ^^^^^^^^^
Error (alert deprecated): Cmdliner.Term.exit_info
Use Cmd.Exit.info instead.
File "bin/pg_check.ml", line 54, characters 6-15:
54 |       exit_info 125 ~doc:"on unexpected internal errors.";
           ^^^^^^^^^
Error (alert deprecated): Cmdliner.Term.exit_info
Use Cmd.Exit.info instead.
File "bin/pg_check.ml", line 64, characters 9-18:
64 | let () = Term.exit @@ Term.eval (cmd, info)
              ^^^^^^^^^
Error (alert deprecated): Cmdliner.Term.exit
Use Stdlib.exit and Cmd.eval instead.
File "bin/pg_check.ml", line 64, characters 22-31:
64 | let () = Term.exit @@ Term.eval (cmd, info)
                           ^^^^^^^^^
Error (alert deprecated): Cmdliner.Term.eval
Use Cmd.v and one of Cmd.eval* instead.
compiling src/pg_query.c              
compiling src/pg_query_split.c
compiling src/pg_query_readfuncs_protobuf.c
Warning: protoc-gen-c not found, skipping protocol buffer regeneration
compiling src/pg_query_scan.c
compiling src/pg_query_outfuncs_json.c
compiling src/pg_query_fingerprint.c
compiling src/pg_query_outfuncs_protobuf.c
compiling src/pg_query_normalize.c
compiling src/pg_query_json_plpgsql.c
compiling src/pg_query_parse.c
compiling src/pg_query_deparse.c
compiling src/pg_query_parse_plpgsql.c
compiling src/postgres/src_backend_utils_fmgr_fmgr.c
compiling src/postgres/src_backend_parser_gram.c
compiling src/postgres/src_common_kwlookup.c
compiling src/postgres/src_backend_commands_define.c
compiling src/postgres/src_common_stringinfo.c
compiling src/postgres/src_pl_plpgsql_src_pl_handler.c
compiling src/postgres/src_backend_utils_mb_mbutils.c
compiling src/postgres/src_backend_storage_lmgr_s_lock.c
compiling src/postgres/src_common_string.c
compiling src/postgres/src_backend_libpq_pqcomm.c
compiling src/postgres/src_backend_catalog_pg_proc.c
compiling src/postgres/src_port_strnlen.c
compiling src/postgres/src_backend_utils_adt_ruleutils.c
compiling src/postgres/src_pl_plpgsql_src_pl_gram.c
compiling src/postgres/src_backend_utils_mmgr_aset.c
compiling src/postgres/src_backend_utils_adt_expandeddatum.c
compiling src/postgres/src_backend_parser_scan.c
compiling src/postgres/src_backend_catalog_namespace.c
compiling src/postgres/src_backend_nodes_equalfuncs.c
compiling src/postgres/src_backend_parser_parse_expr.c
compiling src/postgres/src_backend_nodes_nodeFuncs.c
compiling src/postgres/src_backend_nodes_bitmapset.c
compiling src/postgres/src_backend_parser_parser.c
compiling src/postgres/src_backend_utils_hash_dynahash.c
compiling src/postgres/src_backend_tcop_postgres.c
compiling src/postgres/src_backend_nodes_copyfuncs.c
compiling src/postgres/src_port_strerror.c
compiling src/postgres/src_port_erand48.c
compiling src/postgres/src_backend_utils_init_globals.c
compiling src/postgres/src_port_random.c
compiling src/postgres/src_backend_utils_error_assert.c
compiling src/postgres/src_common_wchar.c
compiling src/postgres/src_pl_plpgsql_src_pl_funcs.c
compiling src/postgres/src_backend_storage_ipc_ipc.c
compiling src/postgres/src_backend_utils_misc_guc.c
compiling src/postgres/src_backend_utils_mmgr_mcxt.c
compiling src/postgres/src_backend_utils_adt_format_type.c
compiling src/postgres/src_backend_nodes_makefuncs.c
compiling src/postgres/src_backend_nodes_value.c
compiling src/postgres/src_backend_utils_error_elog.c
compiling src/postgres/src_pl_plpgsql_src_pl_scanner.c
compiling src/postgres/src_backend_utils_adt_datum.c
compiling src/postgres/src_common_encnames.c
compiling src/postgres/src_port_snprintf.c
compiling src/postgres/src_backend_parser_scansup.c
compiling src/postgres/src_common_psprintf.c
compiling src/postgres/src_backend_nodes_list.c
compiling src/postgres/src_backend_postmaster_postmaster.c
compiling src/postgres/src_pl_plpgsql_src_pl_comp.c
compiling src/postgres/src_port_qsort.c
compiling src/postgres/src_backend_nodes_extensible.c
compiling src/postgres/src_port_pgstrcasecmp.c
compiling src/postgres/src_port_pgsleep.c
compiling src/postgres/src_port_pg_bitutils.c
compiling src/postgres/src_common_keywords.c
compiling vendor/protobuf-c/protobuf-c.c
compiling vendor/xxhash/xxhash.c
Warning: protoc-gen-c not found, skipping protocol buffer regeneration
compiling protobuf/pg_query.pb-c.c
ar: creating libpg_query.a`

Regards!

**Comment by phstrauss** [comment]
Damed code markup!

<pre>
~/Sources/Workbench/pg_query-ocaml-git$ dune build
File "dune-project", line 1, characters 11-16:
1 | (lang dune 2.0.1)
               ^^^^^
Warning: The ".1" part is ignored here.
This version is parsed as just 2.0.
File "test/dune", line 2, characters 8-12:
2 |  (names test)
            ^^^^
Error: No rule found for lib/dllpg_query.so
File "bin/pg_check.ml", line 47, characters 2-11:
47 |   Term.info "pg_check" 
       ^^^^^^^^^
Error (alert deprecated): Cmdliner.Term.info
Use Cmd.info instead.
File "bin/pg_check.ml", line 51, characters 6-15:
51 |       exit_info 0 ~doc:"if all files were parsed successfully.";
           ^^^^^^^^^
Error (alert deprecated): Cmdliner.Term.exit_info
Use Cmd.Exit.info instead.
File "bin/pg_check.ml", line 52, characters 6-15:
52 |       exit_info 1 ~doc:"on parsing errors.";
           ^^^^^^^^^
Error (alert deprecated): Cmdliner.Term.exit_info
Use Cmd.Exit.info instead.
File "bin/pg_check.ml", line 53, characters 6-15:
53 |       exit_info 124 ~doc:"on command line parsing errors.";
           ^^^^^^^^^
Error (alert deprecated): Cmdliner.Term.exit_info
Use Cmd.Exit.info instead.
File "bin/pg_check.ml", line 54, characters 6-15:
54 |       exit_info 125 ~doc:"on unexpected internal errors.";
           ^^^^^^^^^
Error (alert deprecated): Cmdliner.Term.exit_info
Use Cmd.Exit.info instead.
File "bin/pg_check.ml", line 64, characters 9-18:
64 | let () = Term.exit @@ Term.eval (cmd, info)
              ^^^^^^^^^
Error (alert deprecated): Cmdliner.Term.exit
Use Stdlib.exit and Cmd.eval instead.
File "bin/pg_check.ml", line 64, characters 22-31:
64 | let () = Term.exit @@ Term.eval (cmd, info)
                           ^^^^^^^^^
Error (alert deprecated): Cmdliner.Term.eval
Use Cmd.v and one of Cmd.eval* instead.
compiling src/pg_query.c              
compiling src/pg_query_split.c
compiling src/pg_query_readfuncs_protobuf.c
Warning: protoc-gen-c not found, skipping protocol buffer regeneration
compiling src/pg_query_scan.c
compiling src/pg_query_outfuncs_json.c
compiling src/pg_query_fingerprint.c
compiling src/pg_query_outfuncs_protobuf.c
compiling src/pg_query_normalize.c
compiling src/pg_query_json_plpgsql.c
compiling src/pg_query_parse.c
compiling src/pg_query_deparse.c
compiling src/pg_query_parse_plpgsql.c
compiling src/postgres/src_backend_utils_fmgr_fmgr.c
compiling src/postgres/src_backend_parser_gram.c
compiling src/postgres/src_common_kwlookup.c
compiling src/postgres/src_backend_commands_define.c
compiling src/postgres/src_common_stringinfo.c
compiling src/postgres/src_pl_plpgsql_src_pl_handler.c
compiling src/postgres/src_backend_utils_mb_mbutils.c
compiling src/postgres/src_backend_storage_lmgr_s_lock.c
compiling src/postgres/src_common_string.c
compiling src/postgres/src_backend_libpq_pqcomm.c
compiling src/postgres/src_backend_catalog_pg_proc.c
compiling src/postgres/src_port_strnlen.c
compiling src/postgres/src_backend_utils_adt_ruleutils.c
compiling src/postgres/src_pl_plpgsql_src_pl_gram.c
compiling src/postgres/src_backend_utils_mmgr_aset.c
compiling src/postgres/src_backend_utils_adt_expandeddatum.c
compiling src/postgres/src_backend_parser_scan.c
compiling src/postgres/src_backend_catalog_namespace.c
compiling src/postgres/src_backend_nodes_equalfuncs.c
compiling src/postgres/src_backend_parser_parse_expr.c
compiling src/postgres/src_backend_nodes_nodeFuncs.c
compiling src/postgres/src_backend_nodes_bitmapset.c
compiling src/postgres/src_backend_parser_parser.c
compiling src/postgres/src_backend_utils_hash_dynahash.c
compiling src/postgres/src_backend_tcop_postgres.c
compiling src/postgres/src_backend_nodes_copyfuncs.c
compiling src/postgres/src_port_strerror.c
compiling src/postgres/src_port_erand48.c
compiling src/postgres/src_backend_utils_init_globals.c
compiling src/postgres/src_port_random.c
compiling src/postgres/src_backend_utils_error_assert.c
compiling src/postgres/src_common_wchar.c
compiling src/postgres/src_pl_plpgsql_src_pl_funcs.c
compiling src/postgres/src_backend_storage_ipc_ipc.c
compiling src/postgres/src_backend_utils_misc_guc.c
compiling src/postgres/src_backend_utils_mmgr_mcxt.c
compiling src/postgres/src_backend_utils_adt_format_type.c
compiling src/postgres/src_backend_nodes_makefuncs.c
compiling src/postgres/src_backend_nodes_value.c
compiling src/postgres/src_backend_utils_error_elog.c
compiling src/postgres/src_pl_plpgsql_src_pl_scanner.c
compiling src/postgres/src_backend_utils_adt_datum.c
compiling src/postgres/src_common_encnames.c
compiling src/postgres/src_port_snprintf.c
compiling src/postgres/src_backend_parser_scansup.c
compiling src/postgres/src_common_psprintf.c
compiling src/postgres/src_backend_nodes_list.c
compiling src/postgres/src_backend_postmaster_postmaster.c
compiling src/postgres/src_pl_plpgsql_src_pl_comp.c
compiling src/postgres/src_port_qsort.c
compiling src/postgres/src_backend_nodes_extensible.c
compiling src/postgres/src_port_pgstrcasecmp.c
compiling src/postgres/src_port_pgsleep.c
compiling src/postgres/src_port_pg_bitutils.c
compiling src/postgres/src_common_keywords.c
compiling vendor/protobuf-c/protobuf-c.c
compiling vendor/xxhash/xxhash.c
Warning: protoc-gen-c not found, skipping protocol buffer regeneration
compiling protobuf/pg_query.pb-c.c
ar: creating libpg_query.a
</pre>

**Comment by rawleyfowler** [comment]
Just build with release profile.

```
dune build --profile release
```

**Comment by roddyyaga** [comment]
I think this is fixed by #12 (feel free to reopen if it's not).
